### ISSUE TITLE
Gatewayden persiste,  user join message gönderiminde hata

### ISSUE THREAD

**Issue by MuratDoner** [helpfulfamily/clientreactchat#26]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "user" (class family.helpful.persist.message.model.User), not marked as ignorable (15 known properties: "families", "profilePhotoUrl", "currentThankAmount", "createDate", "name", "sentTransactions", "channels", "solutionContents", "solutionTitles", "username", "coverUrl", "problemContents", "problemTitles", "id", "receivedTransactions"])
 at [Source: (byte[])"{"user":{"id":1,"name":null,"createDate":"2019-04-26T20:07:15.000+0000","username":"adminha","profilePhotoUrl":null,"coverUrl":null,"currentThankAmount":null,"sentTransactions":null,"receivedTransactions":null,"problemContents":null,"solutionContents":null,"problemTitles":null,"solutionTitles":null,"channels":[{"id":345,"name":"kanal1234","createDate":"2019-07-11T13:47:12.000+0000","currentObserverAmount":2,"currentThankAmount":7,"user":{"id":1,"name":null,"createDate":"2019-04-26T20:07:15.000+0"[truncated 2241 bytes]; line: 1, column: 10] (through reference chain: family.helpful.persist.message.model.User["user"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar:2.9.8]

**Comment by MuratDoner** [comment]
Yeniden derleyince çözüldü.
